// src/pages/PlayerStatPage.jsx
const partidas = [
    {
      id: 1,
      campeao: "Ahri",
      resultado: "Vitória",
      kda: "10/2/5",
      duracao: "25 min",
      ouro: "12.000",
      dano: "25.000",
      cs: 200,
      visao: 25,
      itens: ["Item1", "Item2", "Item3"],
      spells: ["Flash", "Ignite"],
      imagemCampeao: "ziggs.png",
    },
    {
      id: 2,
      campeao: "Zed",
      resultado: "Derrota",
      kda: "5/8/3",
      duracao: "30 min",
      ouro: "10.000",
      dano: "18.000",
      cs: 180,
      visao: 20,
      itens: ["Item1", "Item2", "Item4"],
      spells: ["Flash", "Teleport"],
      imagemCampeao: "ziggs.png",
    },
    {
      id: 3,
      campeao: "Zed",
      resultado: "Derrota",
      kda: "5/8/3",
      duracao: "30 min",
      ouro: "10.000",
      dano: "18.000",
      cs: 180,
      visao: 20,
      itens: ["Item1", "Item2", "Item4"],
      spells: ["Flash", "Teleport"],
      imagemCampeao: "ziggs.png",
    },
    {
      id: 4,
      campeao: "Zed",
      resultado: "Derrota",
      kda: "5/8/3",
      duracao: "30 min",
      ouro: "10.000",
      dano: "18.000",
      cs: 180,
      visao: 20,
      itens: ["Item1", "Item2", "Item4"],
      spells: ["Flash", "Teleport"],
      imagemCampeao: "ziggs.png",
    },
    {
      id: 5,
      campeao: "Zed",
      resultado: "Derrota",
      kda: "5/8/3",
      duracao: "30 min",
      ouro: "10.000",
      dano: "18.000",
      cs: 180,
      visao: 20,
      itens: ["Item1", "Item2", "Item4"],
      spells: ["Flash", "Teleport"],
      imagemCampeao: "ziggs.png",
    },
    {
      id: 6,
      campeao: "Zed",
      resultado: "Derrota",
      kda: "5/8/3",
      duracao: "30 min",
      ouro: "10.000",
      dano: "18.000",
      cs: 180,
      visao: 20,
      itens: ["Item1", "Item2", "Item4"],
      spells: ["Flash", "Teleport"],
      imagemCampeao: "ziggs.png",
    },
    {
      id: 7,
      campeao: "Zed",
      resultado: "Derrota",
      kda: "5/8/3",
      duracao: "30 min",
      ouro: "10.000",
      dano: "18.000",
      cs: 180,
      visao: 20,
      itens: ["Item1", "Item2", "Item4"],
      spells: ["Flash", "Teleport"],
      imagemCampeao: "ziggs.png",
    },
    {
      id: 8,
      campeao: "Zed",
      resultado: "Derrota",
      kda: "5/8/3",
      duracao: "30 min",
      ouro: "10.000",
      dano: "18.000",
      cs: 180,
      visao: 20,
      itens: ["Item1", "Item2", "Item4"],
      spells: ["Flash", "Teleport"],
      imagemCampeao: "ziggs.png",
    },
    {
      id: 9,
      campeao: "Zed",
      resultado: "Derrota",
      kda: "5/8/3",
      duracao: "30 min",
      ouro: "10.000",
      dano: "18.000",
      cs: 180,
      visao: 20,
      itens: ["Item1", "Item2", "Item4"],
      spells: ["Flash", "Teleport"],
      imagemCampeao: "ziggs.png",
    },
    {
      id: 10,
      campeao: "Zed",
      resultado: "Derrota",
      kda: "5/8/3",
      duracao: "30 min",
      ouro: "10.000",
      dano: "18.000",
      cs: 180,
      visao: 20,
      itens: ["Item1", "Item2", "Item4"],
      spells: ["Flash", "Teleport"],
      imagemCampeao: "ziggs.png",
    },

    // Adicione mais partidas aqui...
  ];
  export default partidas;